### PR TITLE
Fix for missing values in JSON/HTML (fixes #64 and #65)

### LINKED ISSUE #64: Recording of evaluation specifics not in JSON
**Describe the bug**
Content of "Recording of evaluation specifics" is not available in JSON. In JSON under reportFindings there is a key called "evaluationSpecifics" but it's always empty.

**To Reproduce**
1. Go to 'Step 5 Report Findings'
2. Enter something in textarea "Record of evaluation specifics (optional)"
3. Go to "View report" (Step 6)
4. Download JSON
5. Open JSON, no content of Record of Evaluation specifics textarea is available.

**Expected behavior**
As "Record of evaluation specifics" is used to record the evaluation tools, web browsers, assistive technologies, etc" it's the best place to enter used browsers including version numbers. When the JSON is used to import the report data (for example for automation) it's necessary to have this data.

### PR DESCRIPTION
**Pull request by mhansma96**
Added value to Report and download files

fixes #64

### CODE REVIEW

File: src/components/ui/Report.svelte [hunk 1]
```diff
@@ -169,11 +169,18 @@
   <p>{TRANSLATED.TEXT_NO_SAMPLE}</p>
 {/if}
 
-<h2>{TRANSLATED.HEADING_SPECIFICS}</h2>
+<h2>{TRANSLATED.LABEL_TECH}</h2>
 <p>{@html marked(report.specifics) || TRANSLATED.LABEL_NOT_PROVIDED}</p>
 
-<h2>{TRANSLATED.HEADING_RESOURCES}</h2>
-<ul>
+<h2>{TRANSLATED.HEADING_SPECIFICS}</h2>
```
Comment (hidde) [inline src/components/ui/Report.svelte:175]: underneath this heading `report.tech` is displayed, is this the right heading?

File: src/components/ui/Report.svelte [hunk 2]
```diff
@@ -169,11 +169,18 @@
   <p>{TRANSLATED.TEXT_NO_SAMPLE}</p>
 {/if}
 
-<h2>{TRANSLATED.HEADING_SPECIFICS}</h2>
+<h2>{TRANSLATED.LABEL_TECH}</h2>
```
Comment (hidde) [inline src/components/ui/Report.svelte:172]: seems like there's a mismatch between heading and content underneath?

File: src/components/ui/Report.svelte [hunk 3]
```diff
@@ -169,11 +169,18 @@
...
-<h2>{TRANSLATED.HEADING_RESOURCES}</h2>
-<ul>
+<h2>{TRANSLATED.HEADING_SPECIFICS}</h2>
+{#if true}
+  <p>{report.tech}</p>
+{:else}
+  <p>{TRANSLATED.LABEL_NOT_PROVIDED}</p>
+{/if}
+
+<h2 class='strip'>{TRANSLATED.HEADING_RESOURCES}</h2>
```
Comment (hidde) [inline src/components/ui/Report.svelte:182]: I'm probably missing something, but wonder why this section and the list underneath are stripped?

**Review by hidde — CHANGES_REQUESTED** [review]

**Review by hidde — APPROVED** [review]
